### ISSUE TITLE
Python 2.4.3 - python-oauth2 1.5.211

### ISSUE THREAD

**Issue by mem-00** [codebox/reading-list-mover#1]
Hi there,

Python 2.4.3 (Centos 5.8 32) + python-oauth 1.5.211. 

Got always a signature mismatch with instapaper (obviously key and secret are correct). 

e.g.:
content:
 oauth_signature [IP24ANxvMcvAsv2Mahuht1mELOs=] does not match expected value [ebTfCFandT6lZnugGkzcWU8EydU=]
resp:
{'status': '401', 'content-length': '107', 'x-robots-tag': 'noindex', 'x-powered-by': 'a lot of coffee and Phish', 'vary': 'Accept-Encoding', 'server': 'Apache', '-content-encoding': 'gzip', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'date': 'Sat, 12 May 2012 15:29:00 GMT', 'p3p': 'CP="ALL ADM DEV PSAi COM OUR OTRo STP IND ONL"', 'content-type': 'text/html; charset=UTF-8'}

Any clue ?

Thanks in advance.
Kind Regards,
mem

**Comment by codebox** [comment]
Hi,
Are you trying to add urls into Instapaper or read them out? For some reason they will only allow users with Subscription accounts to read urls - users with free accounts can only add single urls into the service, so this may be the problem. See http://www.instapaper.com/api/full under 'Subscription accounts'
Rob

**Comment by mem-00** [comment]
On 12/05/2012 6:24, Rob Dawson wrote:

> Hi,
> Are you trying to add urls into Instapaper or read them out? For some reason they will only allow users with Subscription accounts to read urls - users with free accounts can only add single urls into the service, so this may be the problem. See http://www.instapaper.com/api/full under 'Subscription accounts'
> Rob
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/codebox/reading-list-mover/issues/1#issuecomment-5669709
> Hi Rob,

Just seen that. I finally tested your code with a Python 2.7.2 under 
Windows 7 (still oauth-1.5.211 and simplejson 2.5.2)  and it worked 
first time. Chance that there's a slight incompatibility with Python 
2.4.3 (your code or oauth2) and my guess is something related to 
encoding or quoting.
Shame that instapaper is requiring subscription for so small 
transactions, but I was looking into syncing one way or the other. So 
will try Pocket->Instapaper url by url.

Thanks for answering so quickly.

Cheers.
mem

**Comment by codebox** [comment]
Glad you got it working, thanks for letting me know about the problem
Rob
